#!/usr/bin/env python3
"""Generate manuscript TeX tables from authoritative Stage-C summaries."""

import argparse
import json
from pathlib import Path

from stage_c_publication_contract import PUBLICATION_PANELS


ROOT = Path(__file__).resolve().parent.parent
DEFAULT_PUBLICATION_SUMMARY = (
    ROOT / "benchmark_results/stage_c_publication_comparison/summary.json"
)
DEFAULT_CARRYOVER_SUMMARY = (
    ROOT / "benchmark_results/k1_carryover_joint_factorial/summary.json"
)
DEFAULT_FINAL_OUTPUT = (
    ROOT
    / "benchmark_results/stage_c_publication_comparison/"
    "final_complete_cohort_table.tex"
)
DEFAULT_CARRYOVER_OUTPUT = (
    ROOT
    / "benchmark_results/stage_c_publication_comparison/"
    "k1_carryover_factorial_table.tex"
)
DISPLAY_LABELS = {
    "Ceres": "Ceres",
    "DRS K1 BAE-style": "K1 BAE-style",
    "DRS K1 Schur-PCG": "K1 Schur--PCG",
    "DRS+Schur fast": "DRS+Schur fast",
    "DRS+Schur balanced": "DRS+Schur balanced",
    "DRS+Schur quality": "DRS+Schur quality",
    "DRS K4": "K4 resource",
    "DRS K16": "K16 latency",
    "DRS K4 + terminal correction": "K4 + terminal correction",
    "DRS K16 + terminal correction": "K16 + terminal correction",
}


def display_label(panel, label):
    if label == "Base DRS K24":
        return "Base K24/I200" if panel == "all15_1dsfm" else "Base K24/I90"
    return DISPLAY_LABELS[label]


def load_publication(path):
    summary = json.loads(path.read_text(encoding="utf-8"))
    panels = {}
    for key in ("all15_1dsfm", "all29_bal"):
        contract = PUBLICATION_PANELS[key]
        rows = summary.get(key)
        if not isinstance(rows, list):
            raise ValueError(f"missing publication panel: {key}")
        if tuple(row.get("label") for row in rows) != contract["labels"]:
            raise ValueError(f"publication method coverage mismatch for {key}")
        if any(row.get("scenes") != contract["scenes"] for row in rows):
            raise ValueError(f"publication scene coverage mismatch for {key}")
        panels[key] = rows
    return panels


def load_carryover(path):
    summary = json.loads(path.read_text(encoding="utf-8"))
    if summary.get("status") != "passed":
        raise ValueError("K1 carryover factorial did not pass")
    families = summary.get("families")
    if not isinstance(families, dict) or set(families) != {"1dsfm", "bal"}:
        raise ValueError("K1 carryover family coverage mismatch")
    if families["1dsfm"].get("count") != 15 or families["bal"].get("count") != 29:
        raise ValueError("K1 carryover scene coverage mismatch")
    return families


def format_wtl(values):
    return "/".join(str(value) for value in values)


def write_final_table(output, panels):
    output.write("% Generated by serverTest/build_stage_c_publication_tables.py\n")
    output.write("\\begin{table}[t]\n")
    output.write("  \\centering\n")
    output.write(
        "  \\caption{Final complete-cohort comparison. SSE values are geometric "
        "ratios\\newline to independently evaluated Ceres states; time is "
        "aggregate optimizer time.}\n"
    )
    output.write("  \\label{tab:stage-c-final-reference}\n")
    output.write("  \\scriptsize\n")
    output.write("  \\begin{tabular}{llrrrr}\n")
    output.write("    \\hline\n")
    output.write("    Cohort & Method & SSE/Ceres & SSE/base & W/T/L & Time (s) \\\\\n")
    output.write("    \\hline\n")
    for panel, cohort in (("all15_1dsfm", "1DSfM-15"), ("all29_bal", "BAL-29")):
        for row in panels[panel]:
            sse_base = row["sse_vs_base_geometric"]
            output.write(
                f"    {cohort} & {display_label(panel, row['label'])} & "
                f"{row['sse_vs_ceres_geometric']:.6f} & "
                f"{sse_base:.6f} & "
                f"{format_wtl(row['wins_ties_losses_vs_ceres'])} & "
                f"{row['optimization_seconds']:.3f} \\\\\n"
            )
    output.write("    \\hline\n")
    output.write("  \\end{tabular}\n")
    output.write("\\end{table}\n")


def write_carryover_table(output, families):
    output.write("\\begin{table}[t]\n")
    output.write("  \\centering\n")
    output.write(
        "  \\caption{Copied-baseline K24/I120 K1-carryover factorial. Ratios "
        "below one favor the numerator. S, P, C, and D denote shared-only, "
        "proposal-only, combined, and direct arms. Interaction below one "
        "indicates that the combined effect is better than the product of the "
        "isolated effects.}\n"
    )
    output.write("  \\label{tab:k1-carryover-k24-factorial}\n")
    output.write("  \\scriptsize\n")
    output.write("  \\begin{tabular}{lrrrrrr}\n")
    output.write("    \\hline\n")
    output.write("    Family & S/D & P/D & C/D & P/S & Interaction & C/Ceres \\\\\n")
    output.write("    \\hline\n")
    for family, label in (("1dsfm", "1DSfM-15"), ("bal", "BAL-29")):
        row = families[family]
        output.write(
            f"    {label} & {row['shared_effect']['geometric']:.6f} & "
            f"{row['proposal_effect']['geometric']:.6f} & "
            f"{row['combined_effect']['geometric']:.6f} & "
            f"{row['proposal_under_shared']['geometric']:.6f} & "
            f"{row['interaction_geometric']:.6f} & "
            f"{row['combined_over_ceres']['geometric']:.6f} \\\\\n"
        )
    output.write("    \\hline\n")
    output.write("  \\end{tabular}\n")
    output.write("\\end{table}\n")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--publication-summary", type=Path, default=DEFAULT_PUBLICATION_SUMMARY
    )
    parser.add_argument(
        "--carryover-summary", type=Path, default=DEFAULT_CARRYOVER_SUMMARY
    )
    parser.add_argument("--final-output", type=Path, default=DEFAULT_FINAL_OUTPUT)
    parser.add_argument(
        "--carryover-output", type=Path, default=DEFAULT_CARRYOVER_OUTPUT
    )
    arguments = parser.parse_args()
    panels = load_publication(arguments.publication_summary)
    families = load_carryover(arguments.carryover_summary)
    arguments.final_output.parent.mkdir(parents=True, exist_ok=True)
    with arguments.final_output.open("w", encoding="utf-8") as output:
        write_final_table(output, panels)
    with arguments.carryover_output.open("w", encoding="utf-8") as output:
        write_carryover_table(output, families)
    print(arguments.final_output)
    print(arguments.carryover_output)


if __name__ == "__main__":
    main()
