#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
WORKSPACE=$(cd -- "$SCRIPT_DIR/.." && pwd)
RUNNER="$SCRIPT_DIR/run_drs_failure_top3_live.sh"
ANALYZER="$SCRIPT_DIR/analyze_stage_c_base_backbone_factorial.py"
PYTHON=${PYTHON:-"$SCRIPT_DIR/.venv/bin/python"}
OUTPUT_ROOT=${OUTPUT_ROOT:-"$WORKSPACE/benchmark_results/stage_c_base_backbone_factorial_k24_i30"}
ITERATIONS=${ITERATIONS:-30}
OVERWRITE=${OVERWRITE:-0}
REQUEST_PORT=${REQUEST_PORT:-41220}
CASE_TIMEOUT_SECONDS=${CASE_TIMEOUT_SECONDS:-14400}
FAMILIES=${FAMILIES:-"1dsfm bal"}
MODES=${MODES:-"plain c1 c5 c1_c5"}
ONE_D_SFM_DATASET_LIST_FILE=${ONE_D_SFM_DATASET_LIST_FILE:-"$SCRIPT_DIR/1dsfm_roman_trafalgar_datasets.txt"}
ONE_D_SFM_PROBLEM_FILTER=${ONE_D_SFM_PROBLEM_FILTER:-"roman_forum trafalgar"}
BAL_PROBLEM_FILTER=${BAL_PROBLEM_FILTER:-"52 3068"}
RUN_ANALYZER=${RUN_ANALYZER:-1}
BASE_SHARED_ONLY_CAMERA_PROXIMAL=${BASE_SHARED_ONLY_CAMERA_PROXIMAL:-1}
BASE_METRIC_PROPOSAL_DISAGREEMENT_SCALE=${BASE_METRIC_PROPOSAL_DISAGREEMENT_SCALE:-1.0}
BASE_METRIC_PROPOSAL_DISAGREEMENT_UNTIL=${BASE_METRIC_PROPOSAL_DISAGREEMENT_UNTIL:-0}
BASE_WORKER_OWNED_CAMERAS=${BASE_WORKER_OWNED_CAMERAS:-0}
BASE_VARIANT_PREFIX=${BASE_VARIANT_PREFIX:-base_backbone}
BASE_OUTER_ACCELERATION_UNTIL=${BASE_OUTER_ACCELERATION_UNTIL:-0}
BASE_LOCAL_STATE_REBASE_ITERATION=${BASE_LOCAL_STATE_REBASE_ITERATION:-0}

run_mode() {
  local family=$1 mode=$2 port_offset=$3
  local outer_acceleration=none
  local adaptive_local_depth=0
  local -a family_environment

  case "$mode" in
    plain) ;;
    c1) outer_acceleration=themelis_nesterov ;;
    c5) adaptive_local_depth=1 ;;
    c1_c5)
      outer_acceleration=themelis_nesterov
      adaptive_local_depth=1
      ;;
    *) echo "unknown mode: $mode" >&2; return 2 ;;
  esac

  if [[ "$family" == "1dsfm" ]]; then
    family_environment=(
      ALL_PROBLEMS=0
      DATASET_LIST_FILE="$ONE_D_SFM_DATASET_LIST_FILE"
      PROBLEM_FILTER="$ONE_D_SFM_PROBLEM_FILTER"
    )
  else
    family_environment=(ALL_PROBLEMS=1 DATASET_LIST_FILE= PROBLEM_FILTER="$BAL_PROBLEM_FILTER")
  fi

  env \
    "${family_environment[@]}" \
    OUTPUT_DIR="$OUTPUT_ROOT/$family/$mode" \
    VARIANT_TAG="${BASE_VARIANT_PREFIX}_${mode}" \
    BUNDLE_PALM_REQUEST_PORT="$((REQUEST_PORT + port_offset))" \
    BUNDLE_PALM_RESULT_PORT="$((REQUEST_PORT + port_offset + 1))" \
    BUNDLE_PALM_DIRECT_TANGENT_NORMAL_EQUATIONS=1 \
    BUNDLE_PALM_CAMERA_DIAGONAL_METRIC_SCALE=75 \
    BUNDLE_PALM_CAMERA_TRUST_DIAGONAL_SCALE=1e-4 \
    BUNDLE_PALM_MAXIMUM_TRUST_REGION_RADIUS=1e4 \
    CLUSTERS_LIST=24 ITERATIONS="$ITERATIONS" THREADS_PER_CLUSTER=1 \
    LOCAL_STEPS=1 LOCAL_SOLVER=nesterov \
    NESTEROV_MAX_ITERATIONS=300 ENHANCED_INNER_MAX_ITERATIONS=300 \
    NESTEROV_MIN_ITERATIONS=1 NESTEROV_STOP_TOLERANCE=1e-2 \
    ENHANCED_INNER_UNTIL=30 \
    TRUST_REGION_POLICY=drs PERSISTENT_TRUST_REGION=1 \
    TRUST_REGION_RECOVERY_RATIO=0.5 \
    LOCAL_STATE_REBASE_ITERATION="$BASE_LOCAL_STATE_REBASE_ITERATION" \
    SCENE_NORMALIZATION=points_p95 CAMERA_SCALING=jacobi_initial \
    CAMERA_UPDATE=se3_left CLUSTERING=landmark_scalable \
    PROXIMAL_METRIC=block CONSENSUS_METRIC=full CONSENSUS_EXECUTION=coordinator \
    SHARED_ONLY_CAMERA_PROXIMAL="$BASE_SHARED_ONLY_CAMERA_PROXIMAL" \
    BLOCK_REGULARIZATION=1e-4 BLOCK_CURVATURE_MULTIPLIER=0.4 \
    BLOCK_RECOVERY_MODE=curvature MAXIMUM_BLOCK_CURVATURE_MULTIPLIER=64 \
    CURVATURE_DECAY_AFTER=5 CURVATURE_DECAY_RATIO=0.5 \
    METRIC_PROPOSAL_DISAGREEMENT_SCALE="$BASE_METRIC_PROPOSAL_DISAGREEMENT_SCALE" \
    METRIC_PROPOSAL_DISAGREEMENT_UNTIL="$BASE_METRIC_PROPOSAL_DISAGREEMENT_UNTIL" \
    OUTER_ACCELERATION="$outer_acceleration" LINE_SEARCH_GRID=0,1 \
    OUTER_ACCELERATION_UNTIL="$BASE_OUTER_ACCELERATION_UNTIL" \
    ACCELERATION_RESTART_AFTER=3 \
    ADAPTIVE_LOCAL_DEPTH="$adaptive_local_depth" \
    ADAPTIVE_LOCAL_DEPTH_START=5 ADAPTIVE_LOCAL_DEPTH_MAXIMUM=2 \
    ADAPTIVE_LOCAL_DEPTH_HIGH=0.35 ADAPTIVE_LOCAL_DEPTH_LOW=0.20 \
    ADAPTIVE_LOCAL_DEPTH_WINDOW=3 ADAPTIVE_LOCAL_DEPTH_DWELL=3 \
    SAFEGUARD_MODE=relative DRE_RELATIVE_INCREASE=0.01 \
    MINIMUM_PRIMAL_RATIO=1.001 \
    WORKER_OWNED_LANDMARKS=1 WORKER_OWNED_CAMERAS="$BASE_WORKER_OWNED_CAMERAS" \
    PACKED_REQUEST_BUFFERS=1 DEBUG_OUTPUT=0 LIVE_OUTPUT=0 \
    OVERWRITE="$OVERWRITE" CASE_TIMEOUT_SECONDS="$CASE_TIMEOUT_SECONDS" \
    "$RUNNER"
}

port_offset=0
for family in $FAMILIES; do
  for mode in $MODES; do
    run_mode "$family" "$mode" "$port_offset"
    port_offset=$((port_offset + 2))
  done
done

if [[ "$RUN_ANALYZER" == "1" ]]; then
  "$PYTHON" "$ANALYZER" --root "$OUTPUT_ROOT" --iterations "$ITERATIONS"
fi
echo "Stage-C base-backbone factorial finished: $OUTPUT_ROOT"