#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
WORKSPACE=$(cd -- "$SCRIPT_DIR/.." && pwd)
RUNNER="$SCRIPT_DIR/run_drs_failure_top3_live.sh"
DATASET_LIST_FILE=${DATASET_LIST_FILE:-"$SCRIPT_DIR/1dsfm_roman_trafalgar_datasets.txt"}
PROBLEM_FILTER=${PROBLEM_FILTER:-"roman_forum trafalgar"}
ITERATIONS=${ITERATIONS:-30}
CLUSTERS=${CLUSTERS:-2}
THREADS_PER_CLUSTER=${THREADS_PER_CLUSTER:-12}
OUTPUT_ROOT=${OUTPUT_ROOT:-"$WORKSPACE/benchmark_results/c4_k${CLUSTERS}_postcrash_i${ITERATIONS}"}
REQUEST_PORT=${REQUEST_PORT:-28620}
OVERWRITE=${OVERWRITE:-0}

solvers=(nesterov schur_pcg)
for index in "${!solvers[@]}"; do
  solver=${solvers[$index]}
  env \
    DATASET_LIST_FILE="$DATASET_LIST_FILE" \
    PROBLEM_FILTER="$PROBLEM_FILTER" \
    OUTPUT_DIR="$OUTPUT_ROOT/$solver" \
    VARIANT_TAG="c4_postcrash_${solver}" \
    CAMERA_UPDATE=se3_left \
    CLUSTERS_LIST="$CLUSTERS" \
    BUNDLE_PALM_REQUEST_PORT="$((REQUEST_PORT + 2 * index))" \
    BUNDLE_PALM_RESULT_PORT="$((REQUEST_PORT + 2 * index + 1))" \
    BUNDLE_PALM_DIRECT_TANGENT_NORMAL_EQUATIONS=1 \
    BUNDLE_PALM_DISABLE_LANDMARK_PRECONDITIONING=0 \
    BUNDLE_PALM_LOCAL_SOLVE_METRICS=1 \
    BUNDLE_PALM_DIAGONAL_TRUST_DAMPING=1 \
    BUNDLE_PALM_BAE_TRUST_SCHEDULE=0 \
    BUNDLE_PALM_CUMULATIVE_DIAGONAL_DAMPING=0 \
    BUNDLE_PALM_SCHUR_PCG_RELATIVE_TOLERANCE=0.01 \
    BUNDLE_PALM_SCHUR_PCG_Q_TOLERANCE=0 \
    BUNDLE_PALM_SCHUR_PCG_JACOBI_PRECONDITIONER=0 \
    BUNDLE_PALM_SCHUR_PCG_MAX_ITERATIONS=400 \
    ITERATIONS="$ITERATIONS" \
    THREADS_PER_CLUSTER="$THREADS_PER_CLUSTER" \
    LOCAL_STEPS=1 \
    LOCAL_SOLVER="$solver" \
    NESTEROV_MAX_ITERATIONS=300 \
    NESTEROV_MIN_ITERATIONS=1 \
    NESTEROV_STOP_TOLERANCE=0.01 \
    TRUST_REGION_POLICY=daba \
    PERSISTENT_TRUST_REGION=1 \
    SCENE_NORMALIZATION=points_p95 \
    CAMERA_SCALING=jacobi_initial \
    CLUSTERING=landmark_scalable \
    OUTER_ACCELERATION=none \
    PROXIMAL_METRIC=block \
    CONSENSUS_METRIC=full \
    SHARED_ONLY_CAMERA_PROXIMAL=1 \
    BLOCK_REGULARIZATION=5e-5 \
    BLOCK_CURVATURE_MULTIPLIER=0.00625 \
    MAXIMUM_BLOCK_CURVATURE_MULTIPLIER=64 \
    BLOCK_RECOVERY_MODE=curvature \
    WORKER_OWNED_LANDMARKS=1 \
    WORKER_OWNED_CAMERAS=1 \
    PACKED_REQUEST_BUFFERS=1 \
    DEBUG_OUTPUT=1 \
    LIVE_OUTPUT=0 \
    OVERWRITE="$OVERWRITE" \
    CASE_TIMEOUT_SECONDS=14400 \
    "$RUNNER"
done

echo "C4 K${CLUSTERS} inner comparison finished: $OUTPUT_ROOT"