// pip install protobuf==3.20.3 --upgrade, else does not work with later versions. protoc is too old? but it is the latest version.
syntax = "proto3";

// Complete program to call Ceres on: read in python, send to server that runs optimization.
message program_proto {
  repeated double cameras = 1; // 3d, cameras_s init is by cameras. later extra input.
  repeated double landmarks = 2; // 9d
  repeated double observations = 3; // 2d
  repeated int32 cam_id = 4; // per observation 1 cam
  repeated int32 lm_id = 5;  // per observation 1 landmark
  int32 iterations = 6;
  int32 cluster_id = 7;
  float init_l = 8;
  float be = 9;
  repeated float unorm = 10;
  repeated float vnorm = 11;
  repeated int32 unique_cameras = 12; // should not be many -- if any ever. One could pack cams < 10 lms in one cluster == lms in cam are put in one cluster.
  int32 num_clusters = 13;
  uint64 run_id = 14;
  uint64 phase_id = 15;
}

// sent once
message preconditioning_proto {
  int32 cluster_id = 1;
  repeated double unorm = 2; // must be double
  repeated float vnorm = 3;
}

// message solution_proto {
//   repeated float cameras = 1; // 3d
//   repeated float landmarks = 2; // 9d
// }

// we only return new solution for cameras -- later stepsize as well.
// Test: if we send cameras, we use current program , update cam buffer only and repeat.
// message camera_proto {
//   repeated double cameras = 1; // 3d
// }

// send from master to client
message prox_cluster_proto {
  repeated double cameras   = 1; // 3d actually not needed mostly/always?
  repeated double cameras_s = 2; // 3d
  float be = 3;
  int32 cluster_id = 4;
  int32 revert_lm = 5; // if acc. stepsize is reverted, revert lm as well: 1. Also revert to best solution: 2.
  uint64 run_id = 6;
  uint64 phase_id = 7;
  // clustering: lms by cam. # lms that can fill up cam in cl.
}

// return message from client to master
message return_cluster_proto {
  // repeated float cameras   = 1; // 3d
  // repeated float landmarks = 2; // temporary
  // repeated float step_size = 3;
  repeated double cameras  = 1; // 3d, must be double
  repeated float landmarks = 2; // temporary turn off should still work
  repeated float step_size = 3; // can be float -- actually same perf .. haeh? compress to 2048 or float16
  int32 cluster_id = 4;
  float cost = 5;
  uint64 run_id = 6;
  uint64 phase_id = 7;
}

// send to get cost
message cost_proto {
  repeated double cameras = 1; // 3d, bad is not double -- weird.
  int32 cluster_id = 2;
  int32 revert_lm = 3; // only for cost, revert back after.
  uint64 run_id = 4;
  uint64 phase_id = 5;
}

message return_cost_proto {
  float cost = 1;
  int32 cluster_id = 2;
  uint64 run_id = 3;
  uint64 phase_id = 4;
}

message best_cost_proto {
  float cost = 1;
  int32 cluster_id = 2;
}

// can be one of messages. so proto converts to correct message. client messages server messages
message request_proto {
    oneof options {
        program_proto program = 1;
        //camera_proto cameras = 2;
        prox_cluster_proto update = 3;
        cost_proto cost_update = 4;
        preconditioning_proto preconditioning_update = 5;
        best_cost_proto best_cost = 6;
  }
}

// message serverMessages_proto {
//     repeated float solution = 1;
// }