// pip install protobuf==3.20.3 --upgrade, else does not work with later versions. protoc is too old? but it is the latest version.
syntax = "proto3";

// Complete program to call Ceres on: read in python, send to server that runs optimization.
message program_proto {
  repeated float cameras = 1; // 3d, cameras_s init is by cameras. later extra input.
  repeated float landmarks = 2; // 9d
  repeated float observations = 3; // 2d
  repeated int32 cam_id = 4; // per observation 1 cam
  repeated int32 lm_id = 5;  // per observation 1 landmark
  int32 iterations = 6;
  int32 cluster_id = 7;
  float init_l = 8;
  float be = 9;
  repeated float unorm = 10;
  repeated float vnorm = 11;
  repeated int32 unique_cameras = 12; // should not be many -- if any ever. One could pack cams < 10 lms in one cluster == lms in cam are put in one cluster.
}

message solution_proto {
  repeated float cameras = 1; // 3d
  repeated float landmarks = 2; // 9d
}

// send to get cost
message cost_proto {
  repeated float cameras = 1; // 3d
}

// we only return new solution for cameras -- later stepsize as well.
// Test: if we send cameras, we use current program , update cam buffer only and repeat.
message camera_proto {
  repeated float cameras = 1; // 3d
}

// send from master to client
message prox_cluster_proto {
  repeated float cameras   = 1; // 3d actually not needed
  repeated float cameras_s = 2; // 3d
  float be = 3;
  int32 cluster_id = 4;
  // clustering: lms by cam. # lms that can fill up cam in cl.
}

// return message from client to master
message return_cluster_proto {
  repeated float cameras   = 1; // 3d
  repeated float landmarks = 2; // temporary
  repeated float step_size = 3;
  int32 cluster_id = 4;
  float cost = 5;
}

// can be one of messages. so proto converts to correct message. client messages server messages
message request_proto {
    oneof options {
        program_proto program = 1;
        camera_proto cameras = 2;
        prox_cluster_proto update = 3;
        cost_proto get_cost = 4;
  }
}

message serverMessages_proto {
    repeated float solution = 1;
}